grafana/athena-datasource

go.mod, go.sum, package.json, yarn.lock
Includes the fix for #105 
Additionally using the final version of the frontend version of the grafana-aws-sdk
=> Update SDK versions

src/dashboards/vpc-flow-logs.json, src/plugin.json
The dashboard includes:
- Instructions to set it up.
- A table with some data related to the datasource, table and port selected in the variables.
- A timestream with the same parameters.
Can we add something more?
cc/ @mhausenblas
=> Amazon VPC Flow Logs curated dashboard

cypress/integration/smoke.spec.ts
Update file name for imported provisioning file. See https://github.com/grafana/plugin-provisioning/pull/85
=> Update file name from provisioning repo

.github/workflows/code_coverage.yml
Add workflow to call [grafana/code-coverage workflow](https://github.com/grafana/code-coverage)
=> Add workflow to call common code-coverage workflow

.github/workflows/code_coverage.yml
https://github.com/grafana/code-coverage/releases/tag/v0.1.2
=> Call v0.1.2 code coverage workflow

CHANGELOG.md, package.json
updated package.json and CHANGELOG to release 2.0.0
Adding changes included in #151  as `1.0.6` was not released
=> Prepare 2.0.0 release

.github/workflows/code_coverage.yml
Update code coverage workflow to latest version
=> Update code coverage flow

.github/workflows/code_coverage.yml, cypress/integration/smoke.spec.ts, go.mod, go.sum, package.json, pkg/athena/datasource.go, pkg/athena/datasource_test.go, src/ConfigEditor.tsx, yarn.lock
Will ultimately fix and close https://github.com/grafana/athena-datasource/issues/144
For now a draft until I have tests and have merged and released https://github.com/grafana/grafana-aws-sdk/pull/59
Can be used for for testing ^ by installing the package locally.
=> Use default region in Connect

.github/workflows/code_coverage.yml
Update code coverage workflow to latest version
=> Bump code coverage workflow version

.eslintrc, package.json, yarn.lock
More info in/implements https://github.com/grafana/athena-datasource/issues/29
=> A11y: Add a11y lint plugin

go.mod, go.sum
Upgrade grafana-aws-sdk to update opt-in regions list https://github.com/grafana/grafana-aws-sdk/pull/66
=> Upgrade grafana-aws-sdk to v0.12.0

CHANGELOG.md, cspell.config.json, package.json
Release changes from https://github.com/grafana/athena-datasource/pull/208
Closes https://github.com/grafana/oss-plugin-partnerships/issues/118
=> Prepare v2.5.0 release

CHANGELOG.md, README.md, package.json
Fixes: https://github.com/grafana/oss-plugin-partnerships/issues/122
=> Prepare release v2.8.0

CHANGELOG.md, package.json, yarn.lock
Updates async-query-data dependency with the fix for errors in async queries: https://github.com/grafana/redshift-datasource/issues/209
=> Update async-query-data with a fix for errors

CHANGELOG.md, package.json, yarn.lock
=> Release 2.10.0

CHANGELOG.md, package.json
=> Release 2.10.3

CHANGELOG.md, package.json, yarn.lock
relates to https://github.com/grafana/oss-plugin-partnerships/issues/223
=> Upgrade grafana-aws-sdk

.github/workflows/issue_commands.yml
see https://github.com/grafana/oss-plugin-partnerships/issues/217
=> update workflow token to remove dependency on grafanabot user

package.json, yarn.lock
This resolves some security alerts.
Fixes: 
https://github.com/grafana/oss-plugin-partnerships/issues/440
https://github.com/grafana/oss-plugin-partnerships/issues/443
=> Add debug, underscore to resolutions in package.json

CHANGELOG.md, package.json
Release 2.16.1 and fix up changelog entries
=> Release 2.16.1

package.json, yarn.lock
Use the new version of grafana/aws-sdk with the additional regions that properly displays custom regions
fixes #330
=> Update grafana/aws-sdk to get new regions

README.md
This PR:
- changes Athena to Amazon Athena as per Amazon's documentation
- makes some style and punctuation changes.
=> Update Athena to Amazon Athena

.github/workflows/combine_prs.yml
Whoops 😬 Will remember from now on you can run workflows on branches, to test first.
=> fix "combine PRs" workflow repository name

src/QueryEditorForm.test.tsx, src/QueryEditorForm.tsx, src/types.ts
Before 
https://github.com/user-attachments/assets/7bd008ad-8cc3-4d06-978b-60ccbd286632
After
https://github.com/user-attachments/assets/84a4fbc7-a3c0-4811-9ef4-e08a2d9beff2
Fixes https://github.com/grafana/athena-datasource/issues/291
=> Query Editor: Fix field options not loading in

go.mod, go.sum
=> Bump uber/athenadriver.

CHANGELOG.md, README.md, package.json, src/ConfigEditor.tsx, src/QueryEditor.test.tsx, src/QueryEditorForm.test.tsx, src/QueryEditorForm.tsx, src/ResultReuse/ResultReuse.tsx, src/SQLEditor.tsx, src/VariableQueryEditor.test.tsx, src/language/completionItemProvider.ts, src/language/macros.ts, src/plugin.json
Blocked by https://github.com/grafana/athena-datasource/pull/482
=> Replace @grafana/experimental with @grafana/plugin-ui and prepare 3.0.0

CHANGELOG.md, package.json
- Bugfix: Make sure Athena error object is not nil in [#516](https://github.com/grafana/athena-datasource/pull/516)
=> Prepare 3.1.1

.github/workflows/combine_prs.yml, .github/workflows/detect-breaking-changes.yml, .github/workflows/e2e-tests.yml, .github/workflows/issue_commands.yml, .github/workflows/pr-commands.yml
update actions based on zizmor info
=> Cleanup github actions files

.github/workflows/issue_commands.yml, .github/workflows/pr-commands.yml
TODO for other repos that use this app
=> use vault instead of github secrets
