src/plugin.json

The links section should refer to Athena and not Redshift

Fix the website URL in plugin.json

---

go.mod
go.sum
pkg/athena/api/api.go
pkg/athena/models/settings.go

Ref [#39089](https://github.com/grafana/grafana/issues/39089)
Update `grafana-aws-sdk` to use the backend HTTP client provider.

Update aws-sdk version

---

.github/issue_commands.json

Currently, we automatically add the label `datasource/*` to new issues.
This PR uses the existing GH action already set up to additionally add them to our GH Projects board.
Ideally, this should be done without relying on the `datasource/*` label (since now we have two places where the label is defined: `issue_commands.json` and `1-bug_report.md`) but can use what we have in place for now and come up with another way of doing this later.

chore: add to GH Projects automatically

---

pkg/athena/macros_test.go

Update `$__timeFilter` macro tests with the available usage modes:
1. Without specifying a format: `$__timeFilter(time)`
3. Using the [default format](https://github.com/grafana/athena-datasource/blob/main/pkg/athena/macros.go#L14): `$__timeFilter(time, 'yyyy-MM-dd HH:mm:ss')`
3. With another custom format: `$__timeFilter(time, 'yyyy-MM-dd''T''HH:mm:ss''+0000')`

Update `$__timeFilter` macro tests with the available usage modes

---

CHANGELOG.md
src/plugin.json

Part of https://github.com/grafana/cloud-data-sources/issues/9
> We only want to support the two last major versions of Grafana, so we should update all our plugins so that they specify the minimum grafana version to be >=8.0.0. Releases of these plugins should be synced with grana 9.0.0 stable release (could be a few days after).

Plugin.json : Updated grafana dependency to >=8.0.0

---

.github/workflows/detect-breaking-changes.yml

[Levitate](https://github.com/grafana/levitate) detects if the Grafana APIs your plugin is using are compatible with a certain version of Grafana.
Followed the steps to add this: https://github.com/grafana/grafana-plugin-examples/#api-compatibility

chore: add levitate to detect breaking changes

---

package.json
src/QueryEditor.test.tsx
src/QueryEditor.tsx
yarn.lock

Renders the stop query button only when async query data support is enabled. This is the [PR](https://github.com/grafana/grafana-async-query-data-js/pull/5) that makes the stop button optional.

Show stop query button only for async queries

---

src/datasource.test.ts
src/datasource.ts

Fixes: #192
Queries were not being cancelled when the stop button was pressed. The query was being updated with an empty property when interpolating variables. In-flight queries are kept in a map where the stringified query is used as a key to identify it. When the empty interpolated variable was added to the query, it would cause the key change. E.g. a query `{ table: "table_name" }` would be changed to `{ table: "table_name", column: "" }` (`column` is empty but an property is still added to the query).

Interpolate query properties with variables only if property is set

---

.github/workflows/code_coverage.yml

Update cc workflow to use the latest version running in Node 16: https://github.com/grafana/code-coverage/pull/21

Update code coverage version to 0.1.13

---

src/AnnotationQueryEditor.tsx
src/annotationSupport.ts
src/datasource.ts

Same as [here](https://github.com/grafana/redshift-datasource/pull/206)
In annotations editor we have 3 ways to run a query - with the buttons "Run" and "Cancel", the TEST button, as well as onBlur. This removes the extra buttons, the same as in the Athena variable editor.
Before:
After:

Hide run buttons in annotations

---

cspell.config.json
go.mod
go.sum
pkg/athena/api/api.go
pkg/athena/api/api_test.go
pkg/athena/api/mock/athena-client.go
pkg/athena/datasource.go
pkg/athena/datasource_test.go
pkg/athena/fake/datasource.go
pkg/athena/models/settings.go
pkg/athena/models/settings_test.go
pkg/athena/routes/routes.go
pkg/athena/routes/routes_test.go

Adds backend support for query result reuse.
This depends on https://github.com/grafana/grafana-aws-sdk/pull/71
Fixes: https://github.com/grafana/oss-plugin-partnerships/issues/120
This uses the connection args to set the result reuse configuration. The connection args are per query. The connection args are passed into the `Connect` method for sync queries (this is done in sqlds https://github.com/grafana/sqlds/blob/f35c5a62f66c02aef63b260c1e0a25568ae698b6/datasource.go#L169), and are passed into the `GetAsyncDB` method for async queries (this will be done in grafana-aws-sdk in this PR https://github.com/grafana/grafana-aws-sdk/pull/71/files).
`Connect` and `GetAsyncDB` eventually call [`Settings.Apply`](https://github.com/grafana/grafana-aws-sdk/blob/fdb2a182c315dedb479698d4fdeb0f5af235e2 …

Add Query Result Reuse Support to Backend

---

package.json

- `yarn watch` did not exist, this pr adds this script to run the plugin in watch mode
- `yarn dev` ran the plugin in watch mode, but now builds the plugin in development mode
I think this is more in sync with the instruction in [the contributing guide](https://github.com/grafana/athena-datasource/blob/main/CONTRIBUTING.md)

update package.json per contributing guide

---

CHANGELOG.md
go.mod
go.sum
package.json

- Update grafana-aws-sdk dependency to contain [the most recent fix for async queries](https://github.com/grafana/grafana-aws-sdk/pull/73)
- Prepare release 2.7.0

Update dependencies and prepare release 2.7.0

---

pkg/athena/datasource.go
pkg/athena/datasource_test.go

Connect for the synchronous queries checks and sets a default version(https://github.com/grafana/athena-datasource/pull/168) so GetAsyncDB should also. Technically I haven't found it causing a bug, but I can't see it not being an issue if its an issue for the sync version

Use default region in GetAsyncDB

---

src/QueryEditor.tsx
src/QueryEditorForm.test.tsx
src/QueryEditorForm.tsx
src/ResultReuse/ResultReuse.test.tsx
src/ResultReuse/ResultReuse.tsx
src/ResultReuse/index.ts
src/__mocks__/datasource.ts
src/datasource.test.ts
src/datasource.ts
src/types.ts

Adds a component to the query editor to let the user toggle whether to enable query result reuse and the TTL for reusing query results. If the Athena engine version is 2, then the option is disabled.
Fixes: https://github.com/grafana/oss-plugin-partnerships/issues/121
Fixes: https://github.com/grafana/oss-plugin-partnerships/issues/126
This is a screenshot of the query editor on Athena Engine Version 2 (the reuse result options are disabled and a message is shown to indicate engine version 3 is required for query result reuse)
This is a screenshot of the query editor on Athena Engine Version 3

Add result reuse options to query editor

---

CHANGELOG.md
package.json
yarn.lock

Fixes https://github.com/grafana/oss-plugin-partnerships/issues/163 by updating grafana/aws-sdk-react version to the lates one with the [fix](https://github.com/grafana/grafana-aws-sdk-react/pull/46)

Upgrade aws-sdk to fix React 18 bug

---

CHANGELOG.md
README.md
package.json

This should make sure we have more visibility on the bugfix, since the Readme.md is displayed in the plugin details page: https://grafana.com/grafana/plugins/grafana-athena-datasource/  (that the customer can get to from their "installed plugins" overview)
I put it at the top, but lmk if I should move it

Update readme re:G10

---

go.mod
go.sum

Update to a version of the grafana-aws-sdk where AsyncDatasource handles expression queries correctly.
Part of https://github.com/grafana/grafana-aws-sdk/issues/75

Fix async queries and expressions

---

pkg/athena/api/api.go

The Columns endpoint was not accounting for partition columns. As a result, grafana UI was not able to populate the column drop down with partitions.
**Athena Query UI showing partition columns:**
**Grafana column dropdown omitting partition columns:**

Include partitions as columns

---

CONTRIBUTING.md

This explains how to set up a go workspace which helps when working across some of the backend dependencies without having to modify `go.mod` with `replace`. 
This is for any contributors who build this data source locally. 
Contributes to https://github.com/grafana/oss-plugin-partnerships/issues/146

Add instructions to contributing guide for setting up a go workspace

---

README.md
go.mod
go.sum
package.json
yarn.lock

Updates the dependencies to the versions that support async query caching.
Note that to enable it you need to use enterprise Grafana version 10.1.x, with caching turned on for the Athena datasource and `useCachingService = true` and `awsAsyncQueryCaching = true` in the custom.ini.

Support async query caching

---

go.mod
go.sum
pkg/athena/datasource.go
pkg/athena/datasource_test.go
pkg/athena/models/settings.go

depends on https://github.com/grafana/grafana-aws-sdk/pull/90/files being merged and released.
This fixes the stale token issue by using the last updated time to fetch the cached api objects.
fixes #246

Fix connection error when changing access and secret key

---

pkg/athena/datasource.go
pkg/athena/models/settings.go

I added `Updated` fields to some of the parsing structs in https://github.com/grafana/athena-datasource/pull/262 , but they didn't end up being used. They were accidentally pushed to the pr instead of getting cleaned up

Remove unused "Updated" field from structs

---

CHANGELOG.md
cspell.config.json
package.json
yarn.lock

While testing sandboxing, @kevinwcyu got errors related to use of grafanaBootData in Athena's version of aws-sdk. The package has previously been updated to use config instead of grafanaBootData, so this is just to update the dependency to contain the new code.

Update grafana/aws-sdk dependency and release 2.10.2

---

CHANGELOG.md
go.mod
go.sum
package.json

**What is this feature?**
Update grafana-aws-sdk to v0.19.1 to add `il-central-1` to the opt-in region list
**Which issue(s) does this PR fix?**:
Contributes to https://github.com/grafana/grafana-aws-sdk/issues/94

Update grafana-aws-sdk to v0.19.1 to add `il-central-1` to the opt-in region list

---

CHANGELOG.md
package.json
pkg/athena/routes/routes.go
pkg/athena/routes/routes_test.go
src/ConfigEditor.test.tsx
src/ConfigEditor.tsx
yarn.lock

Adds support for our [new Temporary Credentials Feature](https://github.com/grafana/grafana/pull/75178), currently in Private Preview in Grafana Cloud.
Fixes https://github.com/grafana/oss-plugin-partnerships/issues/259
Adds: 
- new resource route: `/externalId` which fetches external id from the env and returns it if there
- hits that new route whenever we load the Config Editor and the selected auth provider is `Grafana Assume Role`
To Test: 
- use a local version of https://github.com/grafana/grafana-aws-sdk-react/pull/63
- Update Custom.ini:
```
[aws]
allowed_auth_providers = keys,grafana_assume_role
assume_role_enabled = true
external_id = '12345678'
[feature_toggles]
awsDatasourcesTempCredentials = true
```
I think it might be easiest to 
- first approve this pr: 
- then merge and …

Add Support for Temporary Credentials

---

CHANGELOG.md
cspell.config.json
package.json

* Bump go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc from 0.45.0 to 0.46.0 by @dependabot in https://github.com/grafana/athena-datasource/pull/298
* Add debug, underscore to resolutions in package.json by @fridgepoet in https://github.com/grafana/athena-datasource/pull/299

Prepare v2.13.2

---

CHANGELOG.md
package.json
src/QueryEditorForm.test.tsx
src/QueryEditorForm.tsx
src/datasource.test.ts
src/datasource.ts

In the old form styling, `query={queryWithDefaults}`[is passed](https://github.com/grafana/athena-datasource/blob/dc0381a6d45fd5d2419a4262212228c39321bb9e/src/QueryEditorForm.tsx#L291) to the QueryEditor. I mistakenly replaced that with `query={props.query}` in the new styling code. This causes an error on Run query in new form styling if the user doesn't select any of the macros manually:
Additionally, because of this, the autocomplete for the macros doesn't work, as we don't have defaults in the query [to request the data.](https://github.com/grafana/athena-datasource/blob/main/src/SQLEditor.tsx#L21) 
The reason for this is that the connectionArgs (region, table etc.) aren't set to the default value. 
Even the current solution in production isn't ideal, as the user has to change the …

Query Editor improvements: Update query with defaults on mount and filter out empty queries, prepare 2.13.3

---

README.md

https://github.com/grafana/athena-datasource/issues/272
* updates installation, configuration and authentication sections of README.md
* the update of the installation sections is mainly based on https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource/, but skipped the many open source installation options

Update README.md: Updates installation, configuration and authentication

---

CHANGELOG.md
go.mod
go.sum
package.json

Updates the grafana-aws-sdk to the version with the fix for endpoints and assume role.
Fixes #296

Bump grafana-aws-sdk from v0.19.1 to v0.19.3

---

CHANGELOG.md
package.json
yarn.lock

Updates to a version of async-query-data that sets unique prefixes for requestIds.
You can test this by creating a timestream and a athena panel in the same dashboard or creating panels from 2 distinct athena datasources.
Fixes #259 and Fixes https://github.com/grafana/timestream-datasource/issues/273

Bump @grafana/async-query-data from 0.1.10 to 0.1.11

---

pkg/athena/routes/routes.go
pkg/main.go

Previously when saving settings the datasource would be partially rebuild but maintain its connection cache, so if auth-related settings changed the change would not be applied. Now the datasource will be rebuilt entirely.
Fixes #264.

Rebuild the datasource when settings change

---

CHANGELOG.md
CONTRIBUTING.md
package.json

- Fix: Rebuild the datasource when settings change in [#314](https://github.com/grafana/athena-datasource/pull/314)
- Bring in [security fixes in go 1.21.8](https://groups.google.com/g/golang-announce/c/5pwGVUPoMbg)

Prepare 2.13.6

---

CHANGELOG.md
README.md
package.json
src/ConfigEditor.tsx
src/QueryEditor.test.tsx
src/QueryEditor.tsx
src/QueryEditorForm.test.tsx
src/datasource.test.ts
src/datasource.ts
yarn.lock

Did a few things here: 
- remove the athenaAsyncQuerySupport feature toggle
- removed the use of deprecated width-30 class to instead use Grafana theme spacing
- fixed the Run query button to not be disabled if there is no change in the editor. I was kinda bothered by this cause I sometimes just wanted to rerun the same query and not have to go all the way up to the Grafana dashboard refresh button. Also I realized this is how Cloudwatch header buttons work - the Run button is never disabled
https://github.com/grafana/athena-datasource/assets/16140639/97313626-a86a-43c4-9e90-8de583ef618b
I thought the changes were small enough to squeeze in here, but lmk if you'd rather I separate them into 2 or 3 PRs.

Remove the athenaAsyncQuerySupport feature toggle and styling improvements

---

README.md

This PR moves the 'catalog', 'database', and 'workgroup' keys from 'secureJsonData' to 'jsonData' in the 'Using accessKey and secretKey' example.
When using the existing example the values for those keys are not populated.
The other examples have those keys in 'jsonData' also.

docs: fix 'Using accessKey and secretKey' example

---

go.mod
go.sum
pkg/athena/api/api.go

Updates athena-datasource to make use of https://github.com/grafana/grafana-aws-sdk/pull/144.
I don't see any other necessary multitenancy changes, besides the known issue with temporary credentials.

chore: replace GetSession with GetSessionWithAuthSettings

---

README.md

An [issue](https://github.com/grafana/athena-datasource/issues/286) reported adding variables with custom display values doesn't work in Athena or Redshift: 
`SELECT 'foo' AS __text, 'bar' AS __value`
In reality, this isn't a bug but a series of unfortunate events.
1. Grafana docs were misleading and `text` and `value` should be used instead (fixed [here](https://github.com/grafana/grafana/pull/88824))
2. The values must be a field type string. We could add custom logic for both datasources to parse other field types to string; however some other datasources (bigquery and yugabyte) have opted to not do so and defer to the generic Grafana variable code. This means the users are responsible for writing queries that return a string as value. This update in docs reflects that.

Docs; Update template variable docs

---

CHANGELOG.md
package.json
pkg/athena/api/api.go

Fixes: https://github.com/grafana/athena-datasource/issues/338
Uses `ReadAuthSettings` which tries to read auth settings from context first and then automatically falls back to reading auth settings from the environment.
Also includes the changes for releasing these changes.

Fix: use ReadAuthSettings to get authSettings

---

package.json
src/ConfigEditor.test.tsx
src/ConfigEditor.tsx
src/QueryEditorForm.test.tsx
src/QueryEditorForm.tsx
src/ResultReuse/ResultReuse.test.tsx
src/ResultReuse/ResultReuse.tsx
yarn.lock

Removes the newFormStyling feature toggle, making the new styling default. Part of https://github.com/grafana/oss-plugin-partnerships/issues/692

Migrate to new form styling in config and query editors

---

CHANGELOG.md
package.json

-  Migrate to new form styling in config and query editors  in [#337](https://github.com/grafana/athena-datasource/pull/337)

Prepare 2.17.0

---

cspell.config.json
go.mod
go.sum
pkg/athena/api/api.go

This adds errorsource in a few places, in support of better logging & alerting.
Depends on https://github.com/grafana/grafana-aws-sdk/pull/155, and updating `go.mod` to use the new version.

Start adding errorsource

---

pkg/athena/models/settings.go

The latest version of golangci-lint makes this an error, which is why all the recent dependabot PRs are failing.

fix: don't check slice nilness before length check

---

.github/workflows/combine_prs.yml

This adds the "combine PRs" workflow, which will combine all open dependabot PRs (barring merge conflicts) into a single one. This is in support of merging these more regularly.
For now this is set as a manual action. If we decide it's useful we can update it to run weekly.

chore: add manual "combine PRs" action

---

.github/dependabot.yml

I'm getting annoyed by all the failing workflows, I think this should do it? Until we add the new e2e stuff at least
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

Add @grafana/e2e dependencies to dependabot ignore

---

.github/workflows/combine_prs.yml

Makes [the same change as in AMP](https://github.com/grafana/grafana-amazonprometheus-datasource/pull/223):
The current "Combined PRs" title isn't that clear on what's being combined. This title ends up being the default commit message of the squashed commit and ends up in the Changelog..

Update combine_prs action with a clearer PR title

---

CHANGELOG.md
cspell.config.json
package.json

- Update Athena to Amazon Athena
- fix: don't check slice nilness before length check in [#385](https://github.com/grafana/athena-datasource/pull/385)
chore: add manual "combine PRs" action in [#386](https://github.com/grafana/athena-datasource/pull/3586)
- Dependabot updates (some merged via combined PRs):
- [#352](https://github.com/grafana/athena-datasource/pull/352): Bump github.com/aws/aws-sdk-go from 1.51.31 to 1.55.5
- [#362](https://github.com/grafana/athena-datasource/pull/362): Bump typescript from 5.4.5 to 5.5.4
- [#363](https://github.com/grafana/athena-datasource/pull/363): Bump eslint-plugin-prettier from 5.1.3 to 5.2.1
- [#364](https://github.com/grafana/athena-datasource/pull/364): Bump sass-loader from 14.2.1 to 16.0.1
- …

Release 2.17.3

---

CHANGELOG.md
go.mod
go.sum
package.json
pkg/athena/macros.go

These are user errors, so shouldn't be marked as plugin:
- "macro $__timeGroup needs time column and interval"
- "expected at least one argument"
- "expected one argument"
- "expected 1 argument, received %d"
In line 37
```
return 0, "", errors.WithMessagef(err, fmt.Sprintf("error parsing interval %v", args[1]))
```
I'm passing on the message from plugin-sdk ("Invalid interval", "invalid duration") and marking it downstream there: https://github.com/grafana/grafana-plugin-sdk-go/pull/1088

Mark errors when interpolating macros errors as downstream

---

.github/dependabot.yml

- Groups updates according to the package ecosystem
- Sets update interval to be weekly (this will be Mondays by default)

Chore: group dependabot updates and use a weekly interval

---

CHANGELOG.md
package.json

- Bugfix: Bump uber/athenadriver to 1.1.15 (#448)
- Chore: group dependabot updates and use a weekly interval (#443)
- Query Editor: Fix field options not loading in (#437)
- Chore: Update plugin.json keywords (#434)
- Dependabot updates
- Bump @types/node from 22.7.2 to 22.7.5
- Bump @babel/core from 7.25.2 to 7.25.7
- Bump @emotion/css from 11.13.0 to 11.13.4
- Updates @grafana/data from 11.2.1 to 11.2.2
- Updates @grafana/experimental from 2.1.0 to 2.1.1
- Updates @grafana/runtime from 11.2.1 to 11.2.2
- Updates @grafana/schema from 11.2.1 to 11.2.2
- Updates @grafana/ui from 11.2.1 to 11.2.2
- Updates @grafana/aws-sdk from 0.4.2 to 0.5.0
- Bump webpack from 5.94.0 to 5.95.0 
- Bump sass from 1.79.3 to 1.79.4 
- Bump lefthook from 1.7.17 to 1.7.18
- Bump github.com/grafana/sqlds/v4 …

Prepare release 2.17.5

---

.github/dependabot.yml
CHANGELOG.md
package.json

Release 2.18.0 and also updated the dependabot config group names so that dependabot PR will include which package ecosystem the PR is for instead of having all of the PRs don't just refer to `all-dependencies`

Prepare release 2.18.0

---

.github/workflows/e2e-tests.yml
.gitignore
cspell.config.json
package.json
playwright.config.ts
provisioning/datasources/aws-athena.yaml
src/plugin.json
tests/annotationsEditor.spec.ts
tests/configEditor.spec.ts
tests/queryEditor.spec.ts
tests/variableEditor.spec.ts
yarn.lock

What this PR does:
* configures Playwright and `grafana/plugin-e2e` according to [these](https://grafana.com/developers/plugin-tools/e2e-test-a-plugin/migrate-from-grafana-e2e#manually-installing-grafanaplugin-e2e) instructions
* adds simple e2e tests that verifies that the config editor, the query editor, the annotation editor and the variable query editor renders 
* adds a workflow (copied from [this](https://grafana.com/developers/plugin-tools/e2e-test-a-plugin/ci) article) that runs the smoke tests in all versions of Grafana that the plugin supports (decided by the `grafanaDependency` specified in package.json) 
Note that the tests in this PR **only** verifies that the modules used in these frontend components loads and renders in the different Grafana runtimes. It does not verify …

Add e2e smoke tests

---

package.json
src/ConfigEditor.tsx
yarn.lock

Fixes https://github.com/grafana/oss-plugin-partnerships/issues/1125
[Instructions for testing PDC locally](https://wiki.grafana-ops.net/w/index.php/Engineering/Grafana/Data_Sources/API_servers/Testing_datasources_with_PDC_Locally)
New secure socks proxy setting added below the region selector in the config page

Add PDC support

---

CHANGELOG.md
cspell.config.json
package.json

- Implement QueryExecutionError to log downstream error cause in the error response in [#506](https://github.com/grafana/athena-datasource/pull/506)
- Dependabot: 
- Bump github.com/google/go-cmp from 0.6.0 to 0.7.0 in the all-go-dependencies group across 1 directory in [#510](https://github.com/grafana/athena-datasource/pull/510)
- Bump the all-node-dependencies group with 8 updates in [#509](https://github.com/grafana/athena-datasource/pull/509)
- Bump the all-node-dependencies group across 1 directory with 21 updates in [#507](https://github.com/grafana/athena-datasource/pull/507)
- Bump github.com/grafana/grafana-plugin-sdk-go from 0.265.0 to 0.266.0 in the all-go-dependencies group in [#504](https://github.com/grafana/athena-datasource/pull/504)
- Bump dompurify from 3.2.3 to 3.2.4 …

Prepare 3.1.0

---

pkg/athena/api/api.go
pkg/athena/api/api_test.go
pkg/athena/api/mock/athena-client.go

More context in this thread:https://raintank-corp.slack.com/archives/C06TNNEKAHL/p1741876632895959?thread_ts=1741599530.099189&cid=C06TNNEKAHL
Normally AthenaError error wouldn't have nil objects, so this wouldn't happen, but we can't know the cause until we pass the downstream error.

Make sure athena error object is not nil

---

.github/workflows/e2e-tests.yml
.github/workflows/issue_commands.yml
.github/workflows/pr-commands.yml

We exclude grafana/ hashes it in the zizmor config. Also get-vault-secrets needs id-token permission

Github workflows: Don't use hash for grafana actions and add permissions for PRs

---

CHANGELOG.md
cspell.config.json
package.json

- Migrate to aws-sdk-go-v2 in [#491](https://github.com/grafana/athena-datasource/pull/491)
- use vault instead of github secrets in [#534](https://github.com/grafana/athena-datasource/pull/534)
- Add zizmor config in [#537](https://github.com/grafana/athena-datasource/pull/537)
- Cleanup github actions files in [#533](https://github.com/grafana/athena-datasource/pull/533)
- Chore: add label to external contributions in [#499](https://github.com/grafana/athena-datasource/pull/499)
- Bump the all-go-dependencies group across 1 directory with 5 updates in [#538](https://github.com/grafana/athena-datasource/pull/538)
- Bump golang.org/x/net from 0.36.0 to 0.38.0 in the go_modules group in [#528](https://github.com/grafana/athena-datasource/pull/528)
- Bump the all-node-dependencies group …

Prepare 3.1.2

---

CHANGELOG.md
go.mod
go.sum
package.json

This brings in https://github.com/grafana/grafana-aws-sdk/pull/246, which should fix the reported issues with Workspace IAM Role authentication.
Also prepares for the v3.1.3 release.
Fixes: #541

Bump grafana aws sdk to pick up v2 auth fix

---

CHANGELOG.md
go.mod
go.sum
package.json
pkg/athena/api/api.go

Updates for https://github.com/grafana/grafana-aws-sdk/pull/248 , which fetches the grafana assume role external id off the context when we need it, and otherwise use the user setting

Fix: use user external id if not using assume role

---

go.mod
go.sum

I'm hoping to make a PR back to `uber/athenadriver` from our fork soon, to hand off the v2 support.

Bump the version of our athenadriver fork

---

CONTRIBUTING.md

I forgot to update the release instructions in the github actions migration PR

Chore: Update CONTRIBUTING.md with release instructions

---

.github/dependabot.yml
.github/workflows/dependabot-reviewer.yml
.github/workflows/e2e-tests.yml
package.json
yarn.lock

Changes:
- Adds support for the cooldown feature for the github-actions, go and npm ecosystems in `.github/dependabot.yml`. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
- Uses the existing workflow to automerge dependabot updates https://github.com/grafana/security-github-actions/blob/main/.github/workflows/dependabot-automerge.yaml
- Downgraded the version of react-router-dom to v6 since we don't actually support v7 yet. We aren't actually using anything specific in react-router-dom so this should be fine since Grafana is actually still on v5.
- I removed the resolutions for dependencies that were added for CVEs or for fixing tests. Running `yarn why` on each of the dependencies listed in the resolutions list showed …

Add support for auto-merging dependabot updates
